name: Track Follower Growth

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every minute.

jobs:
  track_follower_growth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Configure Git
        run: |
          git config user.name "${{ secrets.GIT_USER }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"

      - name: Run script
        env:
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        run: |
          python main.py || exit 0  # Ignore script exit code if no changes to commit

      - name: Commit and push changes
        run: |
          git add follower_count_log.csv
          git commit -m "Update follower count log" || exit 0  # Avoid failure if no changes
          git pull --rebase
          git push

      - name: Print status
        run: |
          git status
